config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  get '/notreturned', to: 'pages#notreturned'
  get 'pages/home'

  resources :books
  resources :rents
  resources :students

  root "rents#index"

  match 'rents(/:id)/bring', to: 'rents#bring', via: [:post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :rents
  validates_presence_of :name

  scope :byname, -> (byname) {where("name LIKE ?","%#{byname.downcase}%" )}

  def active?
    active ? "<font color='green'><strong>&#10004;</strong></font>".html_safe() : "<font color='red'><strong>X</strong></font>".html_safe()
  end

  def blocked?
    blocked ? "<font color='red'><strong>X</strong></font>".html_safe() : "<font color='green'><strong>&#10004;</strong></font>".html_safe()
  end

  def rented
    @r = Rent.where("returned =  ? and bring_back <= ? and student_id = ?", false, Date.today, id)
    if @r.count > 1
      name+" - #{@r.count} Livros pendentes"
    elsif @r.count == 1
      name+" - 1 Livro pendente"
    else
      name
    end
  end

  def pending
    @r = Rent.where("returned =  ? and bring_back <= ? and student_id = ?", false, Date.today, id)
    @r.count
  end

  def name_with_phone
    if phone.blank?
      name
    else
      name.to_s+" - "+phone.to_s
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.where(nil)
    @students = @students.byname(params[:byname]) if params[:byname].present?
    if params[:withorder].present?
      if params[:withorder] == "pending"
        @students = Student.all.sort {|a,b| b.pending <=> a.pending } if params[:withorder] == "pending"
      else
        @students = Student.all.order(params[:withorder])
      end
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @books = Book.where(id: Rent.where(student_id: @student.id).pluck(:book_id))
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :phone, :email, :blocked, :active)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag('Nome:') %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= label_tag('Telefone:') %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= label_tag('Email:') %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= label_tag('Bloqueado') %>
    <%= f.check_box :blocked %>
  </div>

  <div class="field">
    <%= label_tag('Ativo') %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<center>
<h1>Alunos</h1>
<%= form_tag students_path, :method => 'get' do %>
  <h5>
    <%= text_field_tag :byname, params[:byname] %>
    <%= submit_tag "&#128269".html_safe() %>
  </h5>
<% end %>

<%= link_to 'Novo Aluno', new_student_path, class: "button-success pure-button" %>
</center>
<br />
<table>
  <thead>
    <tr>
      <th><%= link_to "Nome", "/students/?withorder=name" %></th>
      <th><%= link_to "Livros pendentes", '/students/?withorder=pending' %></th>
      <th><%= link_to "Bloqueado", "/students/?withorder=blocked" %></th>
      <th><%= link_to "Ativo", "/students/?withorder=active" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td data-label="Nome"><%= student.name %></td>
        <td data-label="Pendente"><%= student.pending %></td>
        <td data-label="Bloqueado"><%= student.blocked? %></td>
        <td data-label="Ativo"><%= student.active? %></td>
        <td><%= link_to 'Ver mais', student, class: "pure-button" %>
        <%= link_to 'Editar', edit_student_path(student), class: "pure-button" %>
        <%= link_to 'Excluir', student, method: :delete, data: { confirm: 'Tem certeza?' }, class: "pure-button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<h1>Novo aluno</h1>

<%= render 'form', student: @student %>

<%= link_to 'Voltar', students_path %>

app/views/students/show.html.erb
<div>
<p>
  <strong>Nome:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Fone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Bloqueado</strong>
  <%= @student.blocked? %>
</p>

<p>
  <strong>Ativo</strong>
  <%= @student.active? %>
</p>
</div>
<%= link_to 'Editar', edit_student_path(@student), class: "pure-button" %> |
<%= link_to 'Voltar', students_path, class: "pure-button" %>
<hr>
<h2>Histórico de livros alugados:</h2>
<%= render 'books/index' %>