config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  get '/notreturned', to: 'pages#notreturned'
  get 'pages/home'

  resources :books
  resources :rents
  resources :students

  root "rents#index"

  match 'rents(/:id)/bring', to: 'rents#bring', via: [:post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :student, class_name: 'Student', foreign_key: 'student_id'
  belongs_to :book, class_name: 'Book', foreign_key: 'book_id'

  validates_presence_of :student_id, :book_id, :bring_back

  def retur
    returned ? "<font color='green'><strong>&#10004;</strong></font>".html_safe() : "<font color='red'><strong>X</strong></font>".html_safe()
  end

end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy, :bring]

  # GET /rents
  # GET /rents.json
  def index
    @rents = Rent.where(returned: false)

  end

  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    @rent = Rent.new
    @rent.bring_back = Date.today + 7
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new(rent_params)
    @book = Book.find(@rent.book_id)
    @book.available = false
    @book.save
    respond_to do |format|
      if @rent.save
        format.html { redirect_to rents_url, notice: 'Criado com sucesso :D' }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        @book = Book.find(@rent.book_id)
        @book.available = true
        @book.save
        format.html { redirect_to @rent, notice: 'Alterado com sucesso  :D' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bring
    @rent.returned = true
    @rent.save

    returnedBook

    respond_to do |format|
      if @rent.bring_back < Date.today
        format.html { redirect_to notreturned_url, notice: 'Obrigado por devolver o livro :)' }
        format.json { head :no_content }
      else
        format.html { redirect_to rents_url, notice: 'Obrigado por devolver o livro :)' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    def returnedBook
      @book = Book.find(@rent.book_id)
      @book.available = true
      @book.save

      @student = Student.find(@rent.student_id)
      @student.blocked = false
      @student.save
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_params
      params.require(:rent).permit(:student_id, :book_id, :returned, :bring_back, :obs)
    end
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<%= form_for(rent) do |f| %>
  <% if rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="pure-form">
  <div class="field">
    <label>Aluno</label>
    <%= f.collection_select(:student_id, Student.where(blocked: false, active: true), :id, :rented, {prompt: "Selecione um aluno"}) %>
  </div>

  <div class="field">
    <label>Livro</label>
    <%= f.collection_select(:book_id, Book.where(available: true), :id, :name, {prompt: "Selecione um livro"}) %>
  </div>

  <div class="field">
    <label>Data de devolução</label>
    <%= f.date_field :bring_back %>
  </div>

  <div class="field">
    <label>Observação</label>
    <%= f.text_area :obs %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>

<% end %>
</div>

app/views/rents/edit.html.erb
<h1>Editar Emprestimo</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Ver Mais', @rent %> |
<%= link_to 'Voltar', rents_path %>

app/views/rents/index.html.erb
<% if @rents.count == 0 %>
<br /><br /><br />
<h1 align='center'>Nenhum Livro Emprestado =,(</h1> <br />
<h2 align='center'>Que tal oferecer um livro pra alguém? ;)</h2>
<center>
<%= link_to 'Novo emprestimo ', new_rent_path, class: "pure-button" %>
</center
<br /><br />
<% else %>
<h1 align=center>Emprestados</h1>
<center>
<%= link_to 'Novo empréstimo', new_rent_path, class: "pure-button" %>
</center
<br /><br />
<table >
  <thead>
    <tr>
      <th>Aluno</th>
      <th>Livro</th>
      <th>Devolveu</th>
      <th>Quando traz de volta</th>
      <th>Observação</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td data-label="Aluno"><%= link_to rent.student.name_with_phone, student_url(rent.student_id) %></td>
        <td data-label="Livro"><%= rent.book.name if rent.book %></td>
        <td data-label="Returned"><%= rent.retur %></td>
        <td data-label="Devolver"><%= rent.bring_back.strftime("%d %b %Y ") %></td>
        <td data-label="Observação"><%= rent.obs %></td>
        <td><%= link_to 'Ver mais', rent, class: "pure-button" %>
            <%= link_to 'Editar', edit_rent_path(rent), class: "pure-button" %>
            <%= button_to "Devolver", form_class: "pure-button", action: :bring, controller: :rents, id: rent.id %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<br>

app/views/rents/new.html.erb
<h1>Novo Emprestimo</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Voltar', rents_path %>

app/views/rents/show.html.erb
<p>
  <strong>Aluno:</strong>
  <%= @rent.student.name if @rent.student %>
</p>

<p>
  <strong>Livro:</strong>
  <%= @rent.book.name if @rent.book %>
</p>

<p>
  <strong>Devolvido:</strong>
  <%= @rent.returned %>
</p>

<p>
  <strong>Devolveu:</strong>
  <%= @rent.bring_back.strftime("%A, %d %b %Y ") %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @rent.obs %>
</p>

<%= link_to 'Editar', edit_rent_path(@rent) %> |
<%= link_to 'Voltar', rents_path %>