config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  get '/notreturned', to: 'pages#notreturned'
  get 'pages/home'

  resources :books
  resources :rents
  resources :students

  root "rents#index"

  match 'rents(/:id)/bring', to: 'rents#bring', via: [:post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :rents

  scope :byname, -> (byname) {where("name LIKE ?","%#{byname.downcase}%" )}

  def available?
    available ? "<font color='green'><strong>&#10004;</strong></font>".html_safe() : "<font color='red'><strong>X</strong></font>".html_safe()
  end

  def active?
    active ? "<font color='green'><strong>&#10004;</strong></font>".html_safe() : "<font color='red'><strong>X</strong></font>".html_safe()
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(nil)
    @books = @books.byname(params[:byname]) if params[:byname].present?
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :available, :active)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "Nome" %>
  </div>

  <div class="field">
    <%= f.text_field :author, placeholder: "Autor" %>
  </div>

  <div class="field">
    <%= f.text_field :description, placeholder: "Descrição" %>
  </div>

  <div class="field">
    <%= f.label :available %>
    <%= f.check_box :available %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Autor</th>
      <th>Descrição</th>
      <th>Disponível</th>
      <th>Ativo</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td data-label="Nome"><%= book.name %></td>
      <td data-label="Autor"><%= book.author %></td>
      <td data-label="Descrição"><%= book.description %></td>
      <td data-label="Disponível"><%= book.available? %></td>
      <td data-label="Ativo"><%= book.active? %></td>
      <td><%= link_to 'Ver mais', book, class: "pure-button"  %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<h1>Editar Livro</h1>

<%= render 'form', book: @book %>

<%= link_to 'Ver Mais', @book %> |
<%= link_to 'Voltar', books_path %>

app/views/books/index.html.erb
<center>
<h1>Livros</h1>
<%= form_tag books_path, :method => 'get' do %>
  <h5>
    <%= text_field_tag :byname, params[:byname] %>
    <%= submit_tag "&#128269".html_safe() %>
  </h5>
<% end %>
<%= link_to 'Novo livro', new_book_path, class: 'pure-button' %>
</center>
<br />
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Autor</th>
      <th>Descrição</th>
      <th>Disponível</th>
      <th>Ativo</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td data-label="Nome"><%= book.name %></td>
        <td data-label="Autor"><%= book.author %></td>
        <td data-label="Descrição"><%= book.description %></td>
        <td data-label="Disponível"><%= book.available? %></td>
        <td data-label="Ativo"><%= book.active? %></td>
        <td><%= link_to 'Ver mais', book, class: "pure-button"  %>
        <%= link_to 'Editar', edit_book_path(book), class: "pure-button"  %>
        <%= link_to 'Excluir', book, method: :delete, data: { confirm: 'Quer mesmo excluir esse livro?' }, class: "pure-button"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form', book: @book %>

<%= link_to 'Voltar', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Disponível:</strong>
  <%= @book.available? %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @book.active? %>
</p>

<%= link_to 'Editar', edit_book_path(@book) %> |
<%= link_to 'Voltar', books_path %>